package com.utility.mail.sql;

import com.utility.mail.helper.Utils;

public class SQL {

	/**
	 * @param args
	 */
	/*
	 * public static void main(String[] args) { // TODO Auto-generated method
	 * stub
	 * 
	 * }
	 */

	public static String preparedSQL(String param1, String param2,String param3,
			String objectType) {
		String sql = "";

		if (objectType.trim().equalsIgnoreCase("ORDER")) {

			sql = "SELECT "
					+ "GLOG_UTIL.REMOVE_DOMAIN(A.ORDER_RELEASE_GID) ORDER_ID,"
					+ "GLOG_UTIL.REMOVE_DOMAIN(B.SOURCE_LOCATION_GID) SOURCE,"
					+ "GLOG_UTIL.REMOVE_DOMAIN(B.DEST_LOCATION_GID) DEST "
					+ "FROM ORDER_RELEASE_REFNUM A,ORDER_RELEASE B "
					+ "WHERE A.ORDER_RELEASE_REFNUM_VALUE='"
					+ param1
					+ "' "
					// +"WHERE A.ORDER_RELEASE_REFNUM_VALUE='20122016-001' "
					+ "AND GLOG_UTIL.REMOVE_DOMAIN(A.ORDER_RELEASE_REFNUM_QUAL_GID)='"
					+ param2
					+ "' "
					+ "AND A.ORDER_RELEASE_GID=B.ORDER_RELEASE_GID AND ROWNUM=1";

		} else if (objectType.trim().equalsIgnoreCase("SHIPMENT")) {
			
			sql = "SELECT "
					+ "GLOG_UTIL.REMOVE_DOMAIN(A.SHIPMENT_GID) SHIPMENT_ID,"
					+ "GLOG_UTIL.REMOVE_DOMAIN(B.SOURCE_LOCATION_GID) SOURCE,"
					+ "GLOG_UTIL.REMOVE_DOMAIN(B.DEST_LOCATION_GID) DEST "
					+ "FROM SHIPMENT_REFNUM A,SHIPMENT B "
					+ "WHERE A.SHIPMENT_REFNUM_VALUE='"
					+ param1
					+ "' "
					// +"WHERE A.SHIPMENT_REFNUM_VALUE='20122016-001' "
					+ "AND GLOG_UTIL.REMOVE_DOMAIN(A.SHIPMENT_REFNUM_QUAL_GID)='"
					+ param2
					+ "' "
					+ "AND A.SHIPMENT_GID=B.SHIPMENT_GID AND ROWNUM=1";
			
			
		}else if (objectType == "ORD_EVENT") {

			/*sql = "SELECT "
					+ param1
					+ " AS ORD_REF_NUM,"
					+ "O.ORDER_RELEASE_XID AS ORDER_ID,"
					+ "GLOG_UTIL.REMOVE_DOMAIN(O.SOURCE_LOCATION_GID) AS ORDER_SOURCE,"
					+ "GLOG_UTIL.REMOVE_DOMAIN(O.DEST_LOCATION_GID) AS ORDER_DEST,"
					+ "CURSOR (SELECT IE.STATUS_CODE_GID AS STATUS_CODE,"
					+ "MAX(IE.I_TRANSACTION_NO) AS ITRN,"
					+ "BS.DESCRIPTION AS STATUS_DESC,"
					+ "L.LOCATION_NAME AS LOC_NAME,"
					+ "SSH.EVENT_LOCATION_GID AS EVENT_LOC,"
					+ "SSH.SHIPMENT_STOP_NUM AS STOPNUM, "
					+ "TO_CHAR(UTC.GET_LOCAL_DATE(IE.EVENTDATE,SSH.EVENT_LOCATION_GID),'DD-MM-YY HH24:MI:SS') AS EVENTDATE,"
					+ "IE.TIME_ZONE_GID AS TIME_ZONE_GID "
					+ "FROM VIEW_SHIPMENT_ORDER_RELEASE V,SHIPMENT S,IE_SHIPMENTSTATUS IE,SS_STATUS_HISTORY SSH,BS_STATUS_CODE BS,LOCATION L "
					+
					// "WHERE V.ORDER_RELEASE_GID='INSCOE.PETCHEM-CHARTER-011' "
					// +
					"WHERE V.ORDER_RELEASE_GID=O.ORDER_RELEASE_GID "
					+ "AND S.SHIPMENT_GID=V.SHIPMENT_GID  "
					+ "AND BS.BS_STATUS_CODE_GID=IE.STATUS_CODE_GID "
					+ "AND IE.I_TRANSACTION_NO = SSH.I_TRANSACTION_NO "
					+ "AND SSH.SHIPMENT_GID=S.SHIPMENT_GID  "
					+ "AND L.LOCATION_GID = SSH.EVENT_LOCATION_GID "
					+ "AND V.PERSPECTIVE='B' AND S.SHIPMENT_TYPE_GID <> 'SECONDARY CHARGE' "
					+ "GROUP BY V.SHIPMENT_GID,IE.STATUS_CODE_GID,BS.DESCRIPTION, L.LOCATION_NAME, SSH.EVENT_LOCATION_GID, SSH.SHIPMENT_STOP_NUM, "
					+ "TO_CHAR(UTC.GET_LOCAL_DATE(IE.EVENTDATE,SSH.EVENT_LOCATION_GID),'DD-MM-YY HH24:MI:SS'),IE.TIME_ZONE_GID "
					+ "ORDER BY V.SHIPMENT_GID ASC, SSH.SHIPMENT_STOP_NUM ASC,ITRN DESC) AS ORD_EVENT "
					+ "FROM ORDER_RELEASE O "
					+
					// "WHERE O.ORDER_RELEASE_GID='INSCOE.PETCHEM-CHARTER-01'"
					"WHERE GLOG_UTIL.REMOVE_DOMAIN(O.ORDER_RELEASE_GID)='"
					+ param2 + "' ";
			
			*/
			
			if(param3=="ALL"){
				param3="1=1";
			}else{				
				param3=Utils.parseString(param3);
				param3="GLOG_UTIL.REMOVE_DOMAIN(B.STATUS_CODE_GID) IN ("+param3+")";
			}
			
			/*sql= "SELECT '"
					+ param1
					+ "' AS ORD_REF_NUM,"
					+ "O.ORDER_RELEASE_XID AS ORDER_ID, "
					+ "GLOG_UTIL.REMOVE_DOMAIN(O.SOURCE_LOCATION_GID) AS ORDER_SOURCE, "
					+ "GLOG_UTIL.REMOVE_DOMAIN(O.DEST_LOCATION_GID) AS ORDER_DEST, "
					+ "CURSOR(SELECT "
					+ "		MAX( A.ITRN) AS ITRN ," 
					+ "		MAX(A.EVENTDATE) AS EVENTDATE, "
					+ "		MAX(A.TIME_ZONE_GID) AS TIME_ZONE_GID, "
					//+ "   --A.SHIPMENT_GID, "
					//+ "   --A.ORDER_RELEASE_GID, "
					+ "     A.STOPNUM, "
					+ "     A.STATUS_CODE, "
					+ "     A.STATUS_DESC, "
					+ "     A.LOC_NAME, "
					+ "		A.EVENT_LOC "
					+ "FROM "
					+ "(SELECT A.I_TRANSACTION_NO AS ITRN, "
					+ "		A.SHIPMENT_GID, "
					+ "		C.ORDER_RELEASE_GID, "
					+ "		A.EVENT_LOCATION_GID AS EVENT_LOC, "
					+ "		A.SHIPMENT_STOP_NUM AS STOPNUM, "
					+ "		B.STATUS_CODE_GID AS STATUS_CODE, "
					+ "		TO_CHAR(UTC.GET_LOCAL_DATE(B.EVENTDATE,A.EVENT_LOCATION_GID),'DD-MM-YY HH24:MI:SS') AS EVENTDATE, "
					+ "		B.TIME_ZONE_GID AS TIME_ZONE_GID, "
					+ "		D.DESCRIPTION AS STATUS_DESC, "
					+ "		E.LOCATION_NAME AS LOC_NAME "
					+ "FROM SS_STATUS_HISTORY A,IE_SHIPMENTSTATUS B,VIEW_SHIPMENT_ORDER_RELEASE C,BS_STATUS_CODE D, LOCATION E,SHIPMENT F "
					+ "WHERE GLOG_UTIL.REMOVE_DOMAIN(C.ORDER_RELEASE_GID)='"+param2+"' "
					//+ "--A.SHIPMENT_GID='IFFCO/LOGISTICS.L170727007' "
					+ "AND A.I_TRANSACTION_NO=B.I_TRANSACTION_NO "
					+ "AND A.SHIPMENT_GID=C.SHIPMENT_GID "
					+ "AND B.STATUS_CODE_GID=D.BS_STATUS_CODE_GID "
					+ "AND A.EVENT_LOCATION_GID=E.LOCATION_GID "
					+ "AND A.SHIPMENT_GID=F.SHIPMENT_GID "
					+ "AND C.SHIPMENT_GID=F.SHIPMENT_GID "
					+ "AND F.PERSPECTIVE='B' "
					+ "AND F.SHIPMENT_TYPE_GID <> 'SECONDARY CHARGE' "
					//+ "AND F.SHIPMENT_NAME='SY_TO_DELIVERY' "
					+ "AND A.SHIPMENT_STOP_NUM IS NOT NULL "
					+ "AND "+param3+" "
					+ "ORDER BY B.EVENTDATE ASC) A "
					+ "GROUP BY "
					//+ "	   --A.TIME_ZONE_GID, "
					//+ "      --A.SHIPMENT_GID, "
					//+ "      --A.ORDER_RELEASE_GID, "
					+ "        A.STOPNUM, "
					+ "        A.STATUS_CODE, "
					+ "        A.STATUS_DESC, "
					+ "        A.LOC_NAME, "
					+ "		   A.EVENT_LOC "
					+ "		   ORDER BY A.STOPNUM ASC) AS ORD_EVENT "
					+ "FROM ORDER_RELEASE O WHERE GLOG_UTIL.REMOVE_DOMAIN(O.ORDER_RELEASE_GID)='"+param2+"' ";*/
			
			sql="SELECT '" 
					+ param1
					+"' AS ORD_REF_NUM,O.ORDER_RELEASE_XID AS ORDER_ID, "
					+ "GLOG_UTIL.REMOVE_DOMAIN(O.SOURCE_LOCATION_GID) AS ORDER_SOURCE, "
					+ "GLOG_UTIL.REMOVE_DOMAIN(O.DEST_LOCATION_GID) AS ORDER_DEST, "
					+ "CURSOR(SELECT "
					+ "MAX( A.ITRN) AS ITRN , "
					+ "MAX(A.EVENTDATE) AS EVENTDATE, "
					+ "MAX(A.TIME_ZONE_GID) AS TIME_ZONE_GID, "
					+ "A.STOPNUM, "
					+ "A.STATUS_CODE, "
					+ "A.STATUS_DESC, "
					+ "A.LOC_NAME, "
					+ "A.EVENT_LOC "
					+ "FROM (SELECT A.I_TRANSACTION_NO AS ITRN, "
					+ "A.SHIPMENT_GID, "
					+ "C.ORDER_RELEASE_GID, "
					+ "A.EVENT_LOCATION_GID AS EVENT_LOC, "
					+ "A.SHIPMENT_STOP_NUM AS STOPNUM, "
					+ "B.STATUS_CODE_GID AS STATUS_CODE, "
					+ "TO_CHAR(UTC.GET_LOCAL_DATE(B.EVENTDATE,A.EVENT_LOCATION_GID),'DD-MM-YY HH24:MI:SS') AS EVENTDATE, "
					+ "B.TIME_ZONE_GID AS TIME_ZONE_GID, "
					+ "D.DESCRIPTION AS STATUS_DESC, "
					+ "E.LOCATION_NAME AS LOC_NAME "
					+ "FROM SS_STATUS_HISTORY A, "
					+ "IE_SHIPMENTSTATUS B, "
					+ "VIEW_SHIPMENT_ORDER_RELEASE C, "
					+ "BS_STATUS_CODE D, "
					+ "LOCATION E, "
					+ "SHIPMENT F, "
					+ "ORDER_RELEASE G, "
					+ "SHIPMENT_STOP H "
					+ "WHERE GLOG_UTIL.REMOVE_DOMAIN(C.ORDER_RELEASE_GID)='"+param2+"' "
					+ "AND A.I_TRANSACTION_NO=B.I_TRANSACTION_NO "
					+ "AND A.SHIPMENT_GID=C.SHIPMENT_GID "
					+ "AND B.STATUS_CODE_GID=D.BS_STATUS_CODE_GID "
					+ "AND A.EVENT_LOCATION_GID=E.LOCATION_GID "
					+ "AND A.SHIPMENT_GID=F.SHIPMENT_GID "
					+ "AND C.SHIPMENT_GID=F.SHIPMENT_GID "
					+ "AND C.ORDER_RELEASE_GID=G.ORDER_RELEASE_GID "
					+ "AND F.SHIPMENT_GID=H.SHIPMENT_GID "
					+ "AND H.STOP_TYPE IN ('P','D','O','PD') "
					+ "AND ((A.EVENT_LOCATION_GID=G.SOURCE_LOCATION_GID OR A.EVENT_LOCATION_GID=G.DEST_LOCATION_GID) "
					+ "OR (A.EVENT_LOCATION_GID IS NOT NULL AND H.STOP_TYPE='O')) "
					+ "AND F.PERSPECTIVE='B' AND F.SHIPMENT_TYPE_GID <> 'SECONDARY CHARGE' "
					+ "AND A.SHIPMENT_STOP_NUM IS NOT NULL "
					+ "AND "+param3+" " 
					+ "ORDER BY B.EVENTDATE ASC) A "
					+ "GROUP BY "
					+ "A.STOPNUM, "
					+ "A.STATUS_CODE, "
					+ "A.STATUS_DESC, "
					+ "A.LOC_NAME, "
					+ "A.EVENT_LOC "
					+ "ORDER BY A.STOPNUM ASC) AS ORD_EVENT FROM ORDER_RELEASE O "
					+ "WHERE GLOG_UTIL.REMOVE_DOMAIN(O.ORDER_RELEASE_GID)='"+param2+"' ";
			

		} else if (objectType == "SHIP_EVENT") {

						
			if(param3=="ALL"){
				param3="1=1";
			}else{				
				param3=Utils.parseString(param3);
				param3="GLOG_UTIL.REMOVE_DOMAIN(B.STATUS_CODE_GID) IN ("+param3+")";
			}
			
			sql= "SELECT '"
					+ param1
					+ "' AS SHIP_REF_NUM,"
					+ "S.SHIPMENT_XID AS SHIPMENT_ID, "
					+ "GLOG_UTIL.REMOVE_DOMAIN(S.SOURCE_LOCATION_GID) AS SHIPMENT_SOURCE, "
					+ "GLOG_UTIL.REMOVE_DOMAIN(S.DEST_LOCATION_GID) AS SHIPMENT_DEST, "
					+ "CURSOR (SELECT "
					+ "		MAX( A.ITRN) AS ITRN ," 
					+ "		MAX(A.EVENTDATE) AS EVENTDATE, "
					+ "		MAX(A.TIME_ZONE_GID) AS TIME_ZONE_GID, "
					//+ "   --A.SHIPMENT_GID, "
					//+ "   --A.ORDER_RELEASE_GID, "
					+ "     A.STOPNUM, "
					+ "     A.STATUS_CODE, "
					+ "     A.STATUS_DESC, "
					+ "     A.LOC_NAME, "
					+ "		A.EVENT_LOC "
					+ "FROM "
					+ "(SELECT A.I_TRANSACTION_NO AS ITRN, "
					+ "		A.SHIPMENT_GID, "
					+ "		C.ORDER_RELEASE_GID, "
					+ "		A.EVENT_LOCATION_GID AS EVENT_LOC, "
					+ "		A.SHIPMENT_STOP_NUM AS STOPNUM, "
					+ "		B.STATUS_CODE_GID AS STATUS_CODE, "
					+ "		TO_CHAR(UTC.GET_LOCAL_DATE(B.EVENTDATE,A.EVENT_LOCATION_GID),'DD-MM-YY HH24:MI:SS') AS EVENTDATE, "
					+ "		B.TIME_ZONE_GID AS TIME_ZONE_GID, "
					+ "		D.DESCRIPTION AS STATUS_DESC, "
					+ "		E.LOCATION_NAME AS LOC_NAME "
					+ "FROM SS_STATUS_HISTORY A,IE_SHIPMENTSTATUS B,VIEW_SHIPMENT_ORDER_RELEASE C,BS_STATUS_CODE D, LOCATION E,SHIPMENT F "
					// "WHERE C.ORDER_RELEASE_GID='"+param2+"' "
					+ "WHERE GLOG_UTIL.REMOVE_DOMAIN(A.SHIPMENT_GID)='"+param2+"' "
					+ "AND A.I_TRANSACTION_NO=B.I_TRANSACTION_NO "
					+ "AND A.SHIPMENT_GID=C.SHIPMENT_GID "
					+ "AND B.STATUS_CODE_GID=D.BS_STATUS_CODE_GID "
					+ "AND A.EVENT_LOCATION_GID=E.LOCATION_GID "
					+ "AND A.SHIPMENT_GID=F.SHIPMENT_GID "
					+ "AND C.SHIPMENT_GID=F.SHIPMENT_GID "
					+ "AND F.PERSPECTIVE='B' "
					+ "AND F.SHIPMENT_TYPE_GID <> 'SECONDARY CHARGE' "
					//+ "AND F.SHIPMENT_NAME='SY_TO_DELIVERY' "
					+ "AND A.SHIPMENT_STOP_NUM IS NOT NULL "
					+ "AND "+param3+" "
					+ "ORDER BY B.EVENTDATE ASC) A "
					+ "GROUP BY "
					//+ "	   --A.TIME_ZONE_GID, "
					//+ "      --A.SHIPMENT_GID, "
					//+ "      --A.ORDER_RELEASE_GID, "
					+ "        A.STOPNUM, "
					+ "        A.STATUS_CODE, "
					+ "        A.STATUS_DESC, "
					+ "        A.LOC_NAME, "
					+ "		   A.EVENT_LOC "
					+ "		   ORDER BY A.STOPNUM ASC) AS SHIP_EVENT "
					+ "FROM SHIPMENT S WHERE GLOG_UTIL.REMOVE_DOMAIN(S.SHIPMENT_GID)='"+param2+"' ";
			

		}

		return sql;
	}

}
